# TRE CAPACITA' DA RICEVERE:
# 1) SCRIVERE PYTHON;
# 2) PRE ANALISI DEI DATI;
# 3) MACHINE LEARNING, DEEP LEAARNING, AI.



# MACHINE LEARNING:
# MACHINE LEARNING: RICEVE DEI DATI ED ELABORA DELLE CONCLUSIONI
# TECNICHE: ALGORITMI
# HA BISOGNO DELL'UMANO PER FUNZIONARE


# DEEP LEARNING:
# DEEP LEARNING: EVOLUZIONE DEL MACHINE LEARNING, COMPRENDE E MODELLA CONOSCENZE COMPLESSE (FA CAPIRE IL PERCHE') 
# RETI NEURALI: COMPOSTO DA STRATI
# IL DEEP LEARNING E' AUTOMATIZZATO
# NON DEVOO LAVORARE SUL CODICE PER AGGIUSTARE GLI ERRORI, IL DEEP LEARNING HA BISOGNO DI TEMPO PER COMPRENDERE DOVE SBAGLIA

# (MACHINE LEARNING E DEEP LEARNING DIFFERISCONO IN DEFINIZIONE SCOPO E TECNICHE)
# (HANNO GLI OBIETTIVI IN COMUNE)

# ADDESTRARE IL DEEP LEARNING:
# IL FULCRO DI TUTTO SONO I DATI

# DENSE:
# DENSE: SERVE A GESTIRE LA COMPLESSITA' DELLE RETI NEURALI
# DENSE: DENSITA' DEI COLLEGAMENTI NEURONALI ALL'INTERNO DELLE RETI

# FLATTEN:
# FLATTEN: PRENDE TUTTI GLI INPUT E LI RENDE UN ARRAY
# FLATTEN: Strato per appiattire input multidimensionali in un vettore monodimensionale.



# TENSOR FLOW
# ELEMENTI FONDAMENTALI:
# TENSORI: LA STRUTTURA DATI DI BASE. E' UN ARRAY MULTIDIMENSIONALE. PUO' AVERE DA 0 A N DIMENSIONI

# GRAFI COMPUTAZIONALI: RAPPRESENTANO LE OPERAZIONI MATEMATICHE 
# PAG 401
# ESECUZIONE EAGER: PERMETTE DI ESEGUIRE IMMEDIATAMENTE LE OPERAZIONI SENZA LA COSTRUZIONE ID UN GRAFO.
# ONDE EVITARE BUG SI E' TORNATO AD UTILIZZARE UN LINGUAGGIO SIMILE A PYTHON



# KERAS:
# E' SCRITTA IN PYTHON, RISPETTA LE REGOLE DI PYTHON, PUO' COMANDARE TENSOR FLOW
# L'API DI KERAS E' MOLTO VICINO ALL'UMANO
# ----------KERAS----------
# GLI ELEMENTI BASE DI KERAS(5):
# -----1)MODELLO SEQUENZIALE;(CONCETTO)
# GLI STRATI SONO ORGANIZZATI IN SEQUENZA LINEARE
# OGNI STRATO HA UN INPUT E OUTPUT SENZA RAMIFICAZIONI O UNIONI
# -----2)MODELLO FUNZIONALE;(CONCETTO)
# CI PERMETTE DI RAMIFICARE, RENDENDO POSSIBILE UN RITORNO INDIETRO O UN SALTO DI RAMO.
# QUESTO APPROCCIO PERMETTE PERCORSI MULTIPLI, INGRESSI E USCITE MULTIPLE
# OFFRE UNA FLESSIBILITA' MAGGIORE E UN MAGGIORE CONTROLLO DELLA STRUTTURA DELLA RETE
# -----3)STRATI:LAYERS;(ANALISI)
# -----4)COMPILAZIONE DEL MODELLO;
# -----5)ADDESTRAMENTO E VALUTAZIONE.

